### ISSUE TITLE
change package name

### ISSUE THREAD

**Issue by francescalb** [emmo-repo/EMMO-python#205]
from emmo import ... suggests that we are importing something from emmo.

We should reconfigure so that we import from another name. E.g. emmopy, ontopy...

**Comment by francescalb** [comment]
@CasperWA @jesper-friis How should we do this in the most practical and intuitive way? 

We could change the folder emmo to emmopy or ontopy so that in order to import one has to call from emmopy import * or from ontopy import *. It is a little confusing that the name of the package when doing pip install is different though. It is possible to rename the whole package, but I am not sure if that is smart to do. It is also a bit confusing that we call it EMMO-python but install it only as emmo

**Comment by CasperWA** [comment]
As a start, I like `ontopy`.

However, I think the solution here might be two separate packages within the same repository. The packages would then be `emmo` or `emmopy` and `ontopy`.
`ontopy` would be dedicated to all the generic extensions to Owlready2 that is currently implemented, and `emmo`/`emmopy` would represent the EMMO-specific parts, the EMMO validator, etc.
The repository name could also change to something more generic, maybe `Python-ontology-tools` or just `OntoPy` or `OntoEmmoPy` or a completely separate dedicated creative name - like `EMMOntoPy`? Or something quite unrelated that's just a name, although that might be counter-productive.

**Comment by francescalb** [comment]
I like EMMOntoPy 😊

In this kind of separation only emmocheck.py would go into emmopy. Although get_ontology has emmo as default.
Would we then prefer to import like this?

Would we prefer to load as:
from ontopy import get_ontology
from emmopy import emmocheck

or have emmontopy.ontopy import get_ontology? This is a it cumbersome I think

**Comment by CasperWA** [comment]
> I like EMMOntoPy 😊
>
> In this kind of separation only emmocheck.py would go into emmopy. Although get_ontology has emmo as default.
> Would we then prefer to import like this?
>
> Would we prefer to load as:
> `from ontopy import get_ontology`
> `from emmopy import emmocheck`
>
> or have emmontopy.ontopy import get_ontology? This is a it cumbersome I think

EMMOOntoPy is then the new standard we may propose :)

`get_ontology` would go into `ontopy`, and a special EMMO-version can be made importable from `emmopy` that defaults to importing EMMO - that's no issue. The main code for the function will be in `ontopy` though.

I by far prefer the first examples you have - that is also my intention with the suggested namespaces - the repository will install 2 separate packages upon installation - or one can choose to only install one of the packages.

**Comment by jesper-friis** [comment]
I like the suggestion of two Python packages; ontopy and emmopy. Since they are developed together, it is convenient to keep them in the same repository with a single version. 

I also like EMMOntoPy - it both sounds good and indicates that it includes both ontopy and emmopy. But it doesn't reduce (or increase) the confusion that the repo and pypi project are named different from the python packages.

I see that we the latest weeks have had about 1 unique clone of EMMO-Python every day. It is not a huge number, but it is still enough that we have to explain change and try to minimise inconvenience. As far as I know will github redirect if you change the name of a repository. Do you know whether pypi do the same?

**Comment by CasperWA** [comment]
All right. Then let me try and make a draft for this new repo layout and setup? Then we can use that draft as a platform to discuss further.

**Comment by francescalb** [comment]
Ok, go ahead, I have to learn to 'grab' issues :)

**Comment by CasperWA** [comment]
Hmm, so I've been looking into this a bit now.
I think I understand "namespacing" better now, and it might not be what we want - indeed, I don't think we can do what I suggested above in a good way with the current tools available to us.

Namespacing means having several separate Python packages (with their own versions) under a common main project name, e.g.:

```python
import project_name.package1
import project_name.package2
```

Here the `package1` and `package2` are names-spaced packages that are versioned and installed separately, but the share the same base namespace: `project_name`.
I don't think this is what we want though? I mean, what should the various names here then be?

`project_name`: `emmontopy` or `ontopy`
`package1`: `emmopy` or `emmo`
`package2`: `ontopy` or `onto`

With these examples it would then be, e.g.:

```python
import emmontopy.ontopy
import emmontopy.emmopy
```

And not, e.g.:

```python
import ontopy
import emmopy
```

To keep this second way, we would need to do some clever tooling in the repository to make sure each package can be installed with a single command (essentially just a little script), but it would be a bit inflexible, I feel.

So what do you think?
There is also an opportunity here to simply use a single package and have the emmo part be a submodule of it, so it would be:

```python
import ontopy
import ontopy.emmo
```

Or `ontopy.emmopy` or similar.

However that doesn't allow sub-versioning of the `emmo` parts - at least not officially when installing, since it will simply be the `ontopy` package.

The final alternative is to create two separate repositories, of course.

What do you think?

**Comment by francescalb** [comment]
At least, two different repositories I find a bit too much.

I think we should ask ourselves what we really want with emmopy?
For me it is an extension of owlready2, to provide tools a functionalities that _we_ want for working with ontologies. Some of these functionalities are emmo-specific (e.g. checking that the ontology is emmo-compliant), others are more general and not necessarily only for emmo-based ontologies. However, we work with emmo-based ontologies so anything we make has to work with emmo (at least).

I find the name emmo a bit confusing as we are not importing anything from the ontology itself. Maybe we should rename it all just to ontopy  and then have things that are only for emmo under there as emmontopy?
e.g. from ontopy import get_ontologies and from ontopy.emmontpy import emmocheck ...

Francesca

**Comment by CasperWA** [comment]
> At least, two different repositories I find a bit too much.
>
> I think we should ask ourselves what we really want with emmopy?
> For me it is an extension of owlready2, to provide tools a functionalities that _we_ want for working with ontologies. Some of these functionalities are emmo-specific (e.g. checking that the ontology is emmo-compliant), others are more general and not necessarily only for emmo-based ontologies. However, we work with emmo-based ontologies so anything we make has to work with emmo (at least).
>
> I find the name emmo a bit confusing as we are not importing anything from the ontology itself. Maybe we should rename it all just to ontopy and then have things that are only for emmo under there as emmontopy?
> e.g. from ontopy import get_ontologies and from ontopy.emmontpy import emmocheck ...

Then I would just use `ontopy.emmopy` since I understood the `emmontopy` to be a name made for the mixed "packages" of `emmopy` and `ontopy`.

Hmm, after some playing around again, I've solved this issue easily - but the one issue that remains is that it can only be versioned once, since it's installed once as `EMMOntoPy`.
So:

```console
$ pip install emmontopy
...
Successfully installed EMMOntoPy-1.0.1
```
 would be the eventual outcome.
After this one will get the separate `ontopy` and `emmopy` packages, so one can do:

```python
from ontopy import get_ontology
from emmopy import emmocheck
```

But both packages come from a single pip installable package "EMMOntoPy".

The main issue I see here is versioning, at least of the EMMOntoPy package. The individual sub-packages could still be versioned on their own, but this versioning would not be relevant when resolving dependencies as the two "packages" are essentially still a single package. Hmm, maybe we can discuss this offline instead as I feel I'm having trouble conveying what I mean here. And it might be faster as well...

**Comment by CasperWA** [comment]
Reference branch: emmo-repo/EMMO-python@cwa/close-205-package-name.
